# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azurepipelines

stages:
  - stage: Build
    displayName: 'Deploy To Dev'
    jobs:
      - job: CopyPublishArtifact
        variables:
          buildConfiguration: 'Release'

        pool:
          vmImage: 'ubuntu-latest'

        steps:
        - task: CopyFiles@2
          displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
          inputs:
            Contents: 'azuredeploy*.json'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact: drop'

  - stage: DeployDev
    displayName: 'Deploy To Dev'
    variables: 
         - group: 'YAML-Releases-Dev'
    jobs:
      - deployment: 
        pool:
          vmImage: 'ubuntu-latest'
        environment: 'Dev'
        strategy:
         runOnce:
           deploy:
             steps:
              - task: replacetokens@3
                inputs:
                  rootDirectory: '$(Pipeline.Workspace)/drop'
                  targetFiles: 'azuredeploy.parameters'
                  encoding: 'auto'
                  writeBOM: true
                  actionOnMissing: 'warn'
                  keepToken: false
                  tokenPrefix: '#'
                  tokenSuffix: '#'
                  useLegacyPattern: false
                  enableTelemetry: true
             
              - task: AzureResourceManagerTemplateDeployment@3
                displayName: 'ARM Template deployment: Resource Group scope'
                inputs:
                  azureResourceManagerConnection: 'arm-template-poc'
                  subscriptionId: '1b7cc8eb-f3b7-475c-8989-310f3375239d'
                  resourceGroupName: 'arm-template-group'
                  location: 'Central US'
                  csmFile: '$(System.DefaultWorkingDirectory)/_arm-template-poc-CI/drop/azuredeploy.json'
                  csmParametersFile: '$(System.DefaultWorkingDirectory)/_arm-template-poc-CI/drop/azuredeploy.parameters.json'

  